package user_test

import (
	"testing"
	"time"

	"github.com/iheanyi-dev/ecommerce-backend/services/identity/domain/user"
)

func TestNewUser_CreatesCompleteUser(t *testing.T) {
	t.Parallel()

	// Arrange
	fullName, err := user.NewFullName("John Doe")
	if err != nil {
		t.Fatalf("failed to create full name: %v", err)
	}

	email, err := user.NewEmail("john@example.com")
	if err != nil {
		t.Fatalf("failed to create email: %v", err)
	}

	passwordHash, err := user.NewPasswordHash("hashed-password")
	if err != nil {
		t.Fatalf("failed to create password hash: %v", err)
	}

	// Act
	newUser, err := user.NewUser(
		fullName,
		email,
		passwordHash,
	)

	// Assert
	if err != nil {
		t.Fatalf("expected user creation to succeed, got error: %v", err)
	}

	if newUser == nil {
		t.Fatal("expected user to be created")
	}

	if newUser.ID().String() == "" {
		t.Fatal("expected user to have an ID")
	}

	if newUser.FullName().String() != "John Doe" {
		t.Fatalf(
			"expected full name %q, got %q",
			"John Doe",
			newUser.FullName().String(),
		)
	}

	if newUser.Email().String() != "john@example.com" {
		t.Fatalf(
			"expected email %q, got %q",
			"john@example.com",
			newUser.Email().String(),
		)
	}

	if newUser.PasswordHash().String() != "hashed-password" {
		t.Fatal("expected password hash to be stored")
	}

	if newUser.Role() != user.RoleUser {
		t.Fatalf(
			"expected newly created user to have role %q, got %q",
			user.RoleUser,
			newUser.Role(),
		)
	}

	if newUser.Status() != user.StatusPendingVerification {
		t.Fatalf(
			"expected newly created user to have status %q, got %q",
			user.StatusPendingVerification,
			newUser.Status(),
		)
	}

	if newUser.CreatedAt().IsZero() {
		t.Fatal("expected CreatedAt to be set")
	}

	if newUser.UpdatedAt().IsZero() {
		t.Fatal("expected UpdatedAt to be set")
	}
}

func TestNewUser_CreatedAndUpdatedTimestampsAreInitiallyEqual(t *testing.T) {
	t.Parallel()

	fullName, _ := user.NewFullName("John Doe")
	email, _ := user.NewEmail("john@example.com")
	passwordHash, _ := user.NewPasswordHash("hashed-password")

	newUser, err := user.NewUser(fullName, email, passwordHash)
	if err != nil {
		t.Fatalf("expected user creation to succeed, got error: %v", err)
	}

	if !newUser.CreatedAt().Equal(newUser.UpdatedAt()) {
		t.Fatal("expected CreatedAt and UpdatedAt to initially be equal")
	}
}

func TestNewUser_GeneratesUniqueIDs(t *testing.T) {
	t.Parallel()

	fullName, _ := user.NewFullName("John Doe")
	email, _ := user.NewEmail("john@example.com")
	passwordHash, _ := user.NewPasswordHash("hashed-password")

	firstUser, err := user.NewUser(fullName, email, passwordHash)
	if err != nil {
		t.Fatalf("failed to create first user: %v", err)
	}

	secondUser, err := user.NewUser(fullName, email, passwordHash)
	if err != nil {
		t.Fatalf("failed to create second user: %v", err)
	}

	if firstUser.ID() == secondUser.ID() {
		t.Fatal("expected users to have unique IDs")
	}
}

func TestNewUser_DoesNotModifySuppliedTimestampValues(t *testing.T) {
	t.Parallel()

	// This test intentionally documents that timestamps are generated by
	// the aggregate rather than supplied by callers during normal creation.
	before := time.Now()

	fullName, _ := user.NewFullName("John Doe")
	email, _ := user.NewEmail("john@example.com")
	passwordHash, _ := user.NewPasswordHash("hashed-password")

	newUser, err := user.NewUser(fullName, email, passwordHash)
	if err != nil {
		t.Fatalf("expected user creation to succeed, got error: %v", err)
	}

	after := time.Now()

	if newUser.CreatedAt().Before(before) || newUser.CreatedAt().After(after) {
		t.Fatal("expected CreatedAt to be generated during user creation")
	}
}

func TestUser_PromoteToVendor_UpdatesUpdatedAt(t *testing.T) {
	t.Parallel()

	// Arrange
	newUser := newTestUser(t)
	originalUpdatedAt := newUser.UpdatedAt()

	time.Sleep(time.Millisecond)

	// Act
	err := newUser.PromoteToVendor()

	// Assert
	if err != nil {
		t.Fatalf("expected promotion to vendor to succeed, got error: %v", err)
	}

	if !newUser.UpdatedAt().After(originalUpdatedAt) {
		t.Fatal("expected UpdatedAt to change after role promotion")
	}
}

func TestUser_PromoteToVendor_WhenAlreadyVendor_ReturnsError(t *testing.T) {
	t.Parallel()

	// Arrange
	newUser := newTestUser(t)

	if err := newUser.PromoteToVendor(); err != nil {
		t.Fatalf("failed to promote user to vendor: %v", err)
	}

	// Act
	err := newUser.PromoteToVendor()

	// Assert
	if err == nil {
		t.Fatal("expected promoting an existing vendor to fail")
	}

	if newUser.Role() != user.RoleVendor {
		t.Fatalf("expected role to remain vendor, got %q", newUser.Role())
	}
}

func newTestUser(t *testing.T) *user.User {
	t.Helper()

	fullName, err := user.NewFullName("John Doe")
	if err != nil {
		t.Fatalf("failed to create full name: %v", err)
	}

	email, err := user.NewEmail("john@example.com")
	if err != nil {
		t.Fatalf("failed to create email: %v", err)
	}

	passwordHash, err := user.NewPasswordHash("hashed-password")
	if err != nil {
		t.Fatalf("failed to create password hash: %v", err)
	}

	newUser, err := user.NewUser(fullName, email, passwordHash)
	if err != nil {
		t.Fatalf("failed to create user: %v", err)
	}

	return newUser
}

func TestUser_PromoteToVendor_WhenAdmin_ReturnsError(t *testing.T) {
	t.Parallel()

	// Arrange
	newUser := newTestUser(t)

	// We cannot directly mutate the role because the aggregate deliberately
	// protects its state. This test will become relevant once the domain
	// provides the privileged admin-assignment operation.
	//
	// The important rule is that PromoteToVendor itself must never be an
	// administrative promotion mechanism.
	_ = newUser
}
func TestUser_ChangeFullName_UpdatesName(t *testing.T) {
	t.Parallel()

	newUser := newTestUser(t)

	newName, err := user.NewFullName("Jane Doe")
	if err != nil {
		t.Fatalf("failed to create new full name: %v", err)
	}

	originalUpdatedAt := newUser.UpdatedAt()

	time.Sleep(time.Millisecond)

	newUser.ChangeFullName(newName)

	if newUser.FullName().String() != "Jane Doe" {
		t.Fatalf(
			"expected full name %q, got %q",
			"Jane Doe",
			newUser.FullName().String(),
		)
	}

	if !newUser.UpdatedAt().After(originalUpdatedAt) {
		t.Fatal("expected UpdatedAt to change")
	}
}

func TestUser_ChangeEmail_UpdatesEmail(t *testing.T) {
	t.Parallel()

	newUser := newTestUser(t)

	newEmail, err := user.NewEmail("jane@example.com")
	if err != nil {
		t.Fatalf("failed to create new email: %v", err)
	}

	newUser.ChangeEmail(newEmail)

	if newUser.Email().String() != "jane@example.com" {
		t.Fatalf(
			"expected email %q, got %q",
			"jane@example.com",
			newUser.Email().String(),
		)
	}
}

func TestUser_ChangePassword_UpdatesPasswordHash(t *testing.T) {
	t.Parallel()

	newUser := newTestUser(t)

	newPasswordHash, err := user.NewPasswordHash("new-hashed-password")
	if err != nil {
		t.Fatalf("failed to create password hash: %v", err)
	}

	newUser.ChangePassword(newPasswordHash)

	if newUser.PasswordHash().String() != "new-hashed-password" {
		t.Fatal("expected password hash to be updated")
	}
}

func TestUser_PromoteToVendor_ChangesRoleToVendor(t *testing.T) {
	t.Parallel()

	newUser := newTestUser(t)

	if newUser.Role() != user.RoleUser {
		t.Fatalf(
			"expected initial role %q, got %q",
			user.RoleUser,
			newUser.Role(),
		)
	}

	err := newUser.PromoteToVendor()
	if err != nil {
		t.Fatalf("expected promotion to succeed, got: %v", err)
	}

	if newUser.Role() != user.RoleVendor {
		t.Fatalf(
			"expected role %q, got %q",
			user.RoleVendor,
			newUser.Role(),
		)
	}
}

func TestUser_PromoteToVendor_CannotBeRepeated(t *testing.T) {
	t.Parallel()

	newUser := newTestUser(t)

	if err := newUser.PromoteToVendor(); err != nil {
		t.Fatalf("failed to promote user: %v", err)
	}

	err := newUser.PromoteToVendor()

	if err != user.ErrUserAlreadyVendor {
		t.Fatalf(
			"expected ErrUserAlreadyVendor, got %v",
			err,
		)
	}
}

func TestUser_Activate_FromPendingVerification(t *testing.T) {
	t.Parallel()

	newUser := newTestUser(t)

	if newUser.Status() != user.StatusPendingVerification {
		t.Fatalf(
			"expected pending verification, got %q",
			newUser.Status(),
		)
	}

	err := newUser.Activate()
	if err != nil {
		t.Fatalf("expected activation to succeed, got: %v", err)
	}

	if newUser.Status() != user.StatusActive {
		t.Fatalf(
			"expected status %q, got %q",
			user.StatusActive,
			newUser.Status(),
		)
	}
}

func TestUser_Suspend_FromActive(t *testing.T) {
	t.Parallel()

	newUser := newTestUser(t)

	if err := newUser.Activate(); err != nil {
		t.Fatalf("failed to activate user: %v", err)
	}

	err := newUser.Suspend()
	if err != nil {
		t.Fatalf("expected suspension to succeed, got: %v", err)
	}

	if newUser.Status() != user.StatusSuspended {
		t.Fatalf(
			"expected status %q, got %q",
			user.StatusSuspended,
			newUser.Status(),
		)
	}
}

func TestUser_Deactivate_FromActive(t *testing.T) {
	t.Parallel()

	newUser := newTestUser(t)

	if err := newUser.Activate(); err != nil {
		t.Fatalf("failed to activate user: %v", err)
	}

	err := newUser.Deactivate()
	if err != nil {
		t.Fatalf("expected deactivation to succeed, got: %v", err)
	}

	if newUser.Status() != user.StatusInactive {
		t.Fatalf(
			"expected status %q, got %q",
			user.StatusInactive,
			newUser.Status(),
		)
	}
}

func TestUser_CannotSuspendPendingVerificationUser(t *testing.T) {
	t.Parallel()

	newUser := newTestUser(t)

	err := newUser.Suspend()

	if err != user.ErrInvalidStatusTransition {
		t.Fatalf(
			"expected ErrInvalidStatusTransition, got %v",
			err,
		)
	}
}

func TestUser_CannotDeactivatePendingVerificationUser(t *testing.T) {
	t.Parallel()

	newUser := newTestUser(t)

	err := newUser.Deactivate()

	if err != user.ErrInvalidStatusTransition {
		t.Fatalf(
			"expected ErrInvalidStatusTransition, got %v",
			err,
		)
	}
}

func TestUser_CannotSuspendSuspendedUser(t *testing.T) {
	t.Parallel()

	newUser := newTestUser(t)

	if err := newUser.Activate(); err != nil {
		t.Fatalf("failed to activate user: %v", err)
	}

	if err := newUser.Suspend(); err != nil {
		t.Fatalf("failed to suspend user: %v", err)
	}

	err := newUser.Suspend()

	if err != user.ErrInvalidStatusTransition {
		t.Fatalf(
			"expected ErrInvalidStatusTransition, got %v",
			err,
		)
	}
}
