package use_cases

import (
	"context"

	"github.com/iheanyi-dev/ecommerce-backend/services/identity/application/ports"
	"github.com/iheanyi-dev/ecommerce-backend/services/identity/domain/user"
)

// ChangePasswordUseCase implements the authenticated user's password
// change workflow.
//
// Password changes are performed against the authenticated user's domain
// aggregate. The plaintext password is used only inside the application
// workflow and never crosses into the persistence layer.
type ChangePasswordUseCase struct {
	userRepository ports.UserRepository
	passwordHasher ports.PasswordHasher
}

// NewChangePasswordUseCase constructs the password change use case.
func NewChangePasswordUseCase(
	userRepository ports.UserRepository,
	passwordHasher ports.PasswordHasher,
) *ChangePasswordUseCase {
	return &ChangePasswordUseCase{
		userRepository: userRepository,
		passwordHasher: passwordHasher,
	}
}

// Execute changes the authenticated user's password.
//
// Workflow:
//
//  1. Parse the authenticated user ID.
//  2. Load the user aggregate.
//  3. Ensure the account is active.
//  4. Verify the current plaintext password against the stored hash.
//  5. Hash the new plaintext password.
//  6. Create a domain PasswordHash value object.
//  7. Change the password on the User aggregate.
//  8. Persist the changed aggregate.
//
// Plaintext passwords never cross the persistence boundary.
func (uc *ChangePasswordUseCase) Execute(
	ctx context.Context,
	userID string,
	currentPassword string,
	newPassword string,
) error {
	// Convert the authenticated identity into the domain UserID value
	// object before accessing the repository.
	id, err := user.UserIDFromString(userID)
	if err != nil {
		return err
	}

	// Load the authenticated user's aggregate.
	existingUser, err := uc.userRepository.FindByID(ctx, id)
	if err != nil {
		return err
	}

	// A missing aggregate means the authenticated identity no longer
	// corresponds to a persisted user.
	if existingUser == nil {
		return ErrUserNotFound
	}

	// Password changes are permitted only for active accounts.
	//
	// Suspended, inactive, and pending-verification accounts must not be
	// allowed to modify their credentials through this workflow.
	if existingUser.Status() != user.StatusActive {
		return ErrAccountNotActive
	}

	// Verify the current password before doing any password hashing or
	// persistence. This ordering is an important security invariant.
	if err := uc.passwordHasher.Verify(
		ctx,
		currentPassword,
		existingUser.PasswordHash().String(),
	); err != nil {
		return err
	}

	// Hash the new password only after the current password has been
	// successfully verified.
	newPasswordHashValue, err := uc.passwordHasher.Hash(
		ctx,
		newPassword,
	)
	if err != nil {
		return err
	}

	// Convert the generated hash into the domain value object.
	newPasswordHash, err := user.NewPasswordHash(newPasswordHashValue)
	if err != nil {
		return err
	}

	// Let the aggregate perform the domain-level password transition.
	//
	// ChangePassword updates both PasswordHash and UpdatedAt.
	existingUser.ChangePassword(newPasswordHash)

	// Persist the changed aggregate.
	//
	// The repository receives the domain object itself, including the
	// UpdatedAt timestamp generated by ChangePassword. The repository
	// does not generate or overwrite that timestamp.
	//
	// The plaintext current and new passwords never reach persistence.
	return uc.userRepository.UpdatePasswordHash(
		ctx,
		existingUser,
	)
}

// Compile-time assertion that the use case satisfies the application
// boundary exposed to the rest of the system.
var _ ports.ChangePasswordService = (*ChangePasswordUseCase)(nil)
