package use_cases

import (
	"context"

	"github.com/iheanyi-dev/ecommerce-backend/services/identity/application/dto"
	"github.com/iheanyi-dev/ecommerce-backend/services/identity/application/ports"
	"github.com/iheanyi-dev/ecommerce-backend/services/identity/domain/user"
)

// UpdateUserProfileUseCase implements the authenticated user's self-service
// profile update workflow.
//
// The use case deliberately works with the authenticated user's ID rather
// than accepting a user ID from the request body. This guarantees that a
// caller can only modify their own profile.
type UpdateUserProfileUseCase struct {
	userRepository ports.UserRepository
}

// NewUpdateUserProfileUseCase constructs the profile update use case.
func NewUpdateUserProfileUseCase(
	userRepository ports.UserRepository,
) *UpdateUserProfileUseCase {
	return &UpdateUserProfileUseCase{
		userRepository: userRepository,
	}
}

// Execute updates the authenticated user's full name.
//
// The user ID comes from the authenticated request context, not from the
// HTTP request body. This prevents a caller from selecting another user's
// account through the profile endpoint.
func (uc *UpdateUserProfileUseCase) Execute(
	ctx context.Context,
	userID string,
	command dto.UpdateUserProfileCommand,
) (dto.UpdateUserProfileResult, error) {
	// Convert the authenticated identity into the domain UserID value object.
	id, err := user.UserIDFromString(userID)
	if err != nil {
		return dto.UpdateUserProfileResult{}, err
	}

	// Validate the new full name through the domain value object.
	fullName, err := user.NewFullName(command.FullName)
	if err != nil {
		return dto.UpdateUserProfileResult{}, err
	}

	// Load the current aggregate so the response represents the persisted
	// account and so immutable fields such as email remain untouched.
	existingUser, err := uc.userRepository.FindByID(ctx, id)
	if err != nil {
		return dto.UpdateUserProfileResult{}, err
	}

	if existingUser == nil {
		return dto.UpdateUserProfileResult{}, ErrUserNotFound
	}

	// Apply the domain behaviour rather than directly changing persistence
	// fields. ChangeFullName also updates the aggregate's UpdatedAt timestamp.
	existingUser.ChangeFullName(fullName)

	// Persist the changed aggregate.
	//
	// The repository receives the domain object itself, including the
	// UpdatedAt timestamp generated by the domain. Persistence does not
	// generate its own timestamp.
	if err := uc.userRepository.UpdateFullName(
		ctx,
		existingUser,
	); err != nil {
		return dto.UpdateUserProfileResult{}, err
	}

	return dto.NewUpdateUserProfileResult(existingUser), nil
}

// Compile-time assertion guarantees that the use case satisfies the
// application service contract.
var _ ports.UpdateUserProfileService = (*UpdateUserProfileUseCase)(nil)
