package ports

import (
	"context"

	"github.com/google/uuid"
)

// StoreImageInput represents an image supplied as part of Store creation.
//
// This is an application-layer representation and deliberately does not
// depend on multipart/form-data, HTTP requests, or any other presentation
// technology.
type StoreImageInput struct {
	// Content contains the image bytes.
	Content []byte

	// Filename is the original filename supplied with the image.
	//
	// It may be useful when determining the image format, but it is not used
	// as the Store's persisted image reference.
	Filename string

	// ContentType identifies the image media type when available.
	ContentType string
}

// StoreImage represents the information required to asynchronously store a
// Store image.
//
// The reference is generated by the Create Store application workflow from
// the newly created Store ID. Storage infrastructure must use this reference
// rather than generating its own Store image name.
type StoreImage struct {
	// StoreID identifies the Store that owns the image.
	StoreID uuid.UUID

	// Reference is the deterministic Store image reference, including its
	// extension.
	Reference string

	// Content contains the image bytes to be stored.
	Content []byte

	// ContentType identifies the image media type.
	ContentType string
}

// ImageStorageDispatcher asynchronously dispatches Store image storage.
//
// The application depends only on this capability. The infrastructure
// implementation decides whether the asynchronous work is performed by an
// in-process worker, message broker, or another mechanism.
type ImageStorageDispatcher interface {
	// DispatchStoreImage schedules the image for asynchronous storage.
	//
	// Dispatch failure is not a Create Store failure. The Store has already
	// completed its synchronous creation workflow at this point.
	DispatchStoreImage(ctx context.Context, image StoreImage) error
}
